// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckWritePermission(arg1) {
  return window['go']['main']['App']['CheckWritePermission'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function Install(arg1, arg2, arg3) {
  return window['go']['main']['App']['Install'](arg1, arg2, arg3);
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function PerformUninstall() {
  return window['go']['main']['App']['PerformUninstall']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}
