// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDictionaryWord(arg1:string):Promise<void>;

export function AddTransliteration(arg1:string,arg2:string):Promise<void>;

export function DeleteDictionaryWord(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeleteRecording(arg1:number):Promise<void>;

export function DeleteTransliteration(arg1:string):Promise<void>;

export function DownloadEssentialAssets():Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function GetAnalytics():Promise<Array<main.Analytics>>;

export function GetConfig():Promise<main.Config>;

export function GetDictionaryWords():Promise<Array<string>>;

export function GetGPUDevices():Promise<Array<string>>;

export function GetInitialRoute():Promise<string>;

export function GetMicrophones():Promise<Array<string>>;

export function GetModelsList():Promise<Array<main.ModelStatus>>;

export function GetPlatform():Promise<string>;

export function GetProfileName():Promise<string>;

export function GetRecordings():Promise<Array<main.Recording>>;

export function GetTransliterations():Promise<Array<main.WordMapping>>;

export function GetUpdateStatus():Promise<main.UpdateState>;

export function GetVersion():Promise<string>;

export function InstallUpdateAndRestart():Promise<void>;

export function IsSetupCompleted():Promise<boolean>;

export function PurgeNow():Promise<void>;

export function SelectDataFolder():Promise<string>;

export function SetActiveModel(arg1:string):Promise<void>;

export function SetDataFolder(arg1:string):Promise<void>;

export function SetInputBoost(arg1:boolean,arg2:number):Promise<void>;

export function SetKeybindCaptureActive(arg1:boolean):Promise<void>;

export function SetKeybinds(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function SetLLMContextSize(arg1:number):Promise<void>;

export function SetLLMEnableThinking(arg1:boolean):Promise<void>;

export function SetLLMEnabled(arg1:boolean):Promise<void>;

export function SetLLMRefinementMode(arg1:string):Promise<void>;

export function SetLLMTone(arg1:string):Promise<void>;

export function SetManglishEnabled(arg1:boolean):Promise<void>;

export function SetManglishExamples(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetMicrophone(arg1:string):Promise<void>;

export function SetProcessingEngine(arg1:string):Promise<void>;

export function SetProfileName(arg1:string):Promise<void>;

export function SetRetention(arg1:number,arg2:number):Promise<void>;

export function SetSelectedGPU(arg1:string):Promise<void>;

export function SetStartMinimized(arg1:boolean):Promise<void>;

export function SetStartOnStartup(arg1:boolean):Promise<void>;

export function UpdateRecording(arg1:number,arg2:string):Promise<void>;
