// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModel(arg1) {
  return window['go']['main']['SettingsApp']['DeleteModel'](arg1);
}

export function DownloadEssentialAssets() {
  return window['go']['main']['SettingsApp']['DownloadEssentialAssets']();
}

export function DownloadModel(arg1) {
  return window['go']['main']['SettingsApp']['DownloadModel'](arg1);
}

export function GetAnalytics() {
  return window['go']['main']['SettingsApp']['GetAnalytics']();
}

export function GetConfig() {
  return window['go']['main']['SettingsApp']['GetConfig']();
}

export function GetGPUDevices() {
  return window['go']['main']['SettingsApp']['GetGPUDevices']();
}

export function GetInitialRoute() {
  return window['go']['main']['SettingsApp']['GetInitialRoute']();
}

export function GetMicrophones() {
  return window['go']['main']['SettingsApp']['GetMicrophones']();
}

export function GetModelsList() {
  return window['go']['main']['SettingsApp']['GetModelsList']();
}

export function GetPlatform() {
  return window['go']['main']['SettingsApp']['GetPlatform']();
}

export function GetProfileName() {
  return window['go']['main']['SettingsApp']['GetProfileName']();
}

export function GetRecordings() {
  return window['go']['main']['SettingsApp']['GetRecordings']();
}

export function IsSetupCompleted() {
  return window['go']['main']['SettingsApp']['IsSetupCompleted']();
}

export function PurgeNow() {
  return window['go']['main']['SettingsApp']['PurgeNow']();
}

export function SelectDataFolder() {
  return window['go']['main']['SettingsApp']['SelectDataFolder']();
}

export function SetActiveModel(arg1) {
  return window['go']['main']['SettingsApp']['SetActiveModel'](arg1);
}

export function SetDataFolder(arg1) {
  return window['go']['main']['SettingsApp']['SetDataFolder'](arg1);
}

export function SetInputBoost(arg1, arg2) {
  return window['go']['main']['SettingsApp']['SetInputBoost'](arg1, arg2);
}

export function SetKeybindCaptureActive(arg1) {
  return window['go']['main']['SettingsApp']['SetKeybindCaptureActive'](arg1);
}

export function SetKeybinds(arg1, arg2, arg3, arg4) {
  return window['go']['main']['SettingsApp']['SetKeybinds'](arg1, arg2, arg3, arg4);
}

export function SetMicrophone(arg1) {
  return window['go']['main']['SettingsApp']['SetMicrophone'](arg1);
}

export function SetProcessingEngine(arg1) {
  return window['go']['main']['SettingsApp']['SetProcessingEngine'](arg1);
}

export function SetProfileName(arg1) {
  return window['go']['main']['SettingsApp']['SetProfileName'](arg1);
}

export function SetRetention(arg1, arg2) {
  return window['go']['main']['SettingsApp']['SetRetention'](arg1, arg2);
}

export function SetSelectedGPU(arg1) {
  return window['go']['main']['SettingsApp']['SetSelectedGPU'](arg1);
}

export function SetStartMinimized(arg1) {
  return window['go']['main']['SettingsApp']['SetStartMinimized'](arg1);
}

export function SetStartOnStartup(arg1) {
  return window['go']['main']['SettingsApp']['SetStartOnStartup'](arg1);
}
